### ISSUE TITLE
Package removed from CRAN, please fix!

### ISSUE THREAD

**Issue by mrismailt** [fvlampe/goeveg#8]
Hi! We have a production app that depends on this package to run. The package seems to have been removed from CRAN (https://cran.r-project.org/package=goeveg) due to: "issues were not corrected despite reminders". Would you guys be able to fix this? Let me know if you need any help. Thanks!

**Comment by fvlampe** [comment]
Hi! Which functions is your app using? Sorry for that, the problem is the use of order() on a data frame with k rows and 1 column in the function synsort(), which was working well until now but apparently is a problem in the new R version. As we didn't have the time yet to fix this (and also need to think about how to do it differently), the package was removed. I will upload it again to CRAN in April, probably without synsort() and syntable() if we cannot fix it until then. If you have any ideas to fix the code to work again without warnings "cannot xtfrm data frames", we are happy about your suggestions! Thanks.

**Comment by fvlampe** [comment]
package is on CRAN again...
